

# This file was *autogenerated* from the file rsa_gen.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_2 = Integer(2)
import binascii


def msg_to_int(msg):
    int_msg = ""
    for ch in msg:
        pre = "{0:b}".format(ord(ch))
        if len(pre) < _sage_const_7 :
            pre = "0" * (_sage_const_7  - len(pre)) + pre
        int_msg += pre

    return int(int_msg, _sage_const_2 )



print(msg_to_int("hello"))

